// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArUFvt4Qo_iqvEov442wEKAA-ASeVmEQs',
    appId: '1:198328821100:web:afc7340b164d4f69f93f49',
    messagingSenderId: '198328821100',
    projectId: 'crud-19417',
    authDomain: 'crud-19417.firebaseapp.com',
    storageBucket: 'crud-19417.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ffZP6_TytJrMLCPnXKGSUsrBe8nO2cw',
    appId: '1:686950052046:ios:3ed6a57a78fb9ff2ee209f',
    messagingSenderId: '686950052046',
    projectId: 'flutter-project-af49b',
    storageBucket: 'flutter-project-af49b.appspot.com',
    iosClientId: '686950052046-1fck32f40m2agtrnjhgbdfv6r4e0d26a.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcmCnlZ0lJObSIxRW4ytm0X1PUY7a_geY',
    appId: '1:198328821100:ios:8f9d50ee65441f01f93f49',
    messagingSenderId: '198328821100',
    projectId: 'crud-19417',
    storageBucket: 'crud-19417.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArUFvt4Qo_iqvEov442wEKAA-ASeVmEQs',
    appId: '1:198328821100:web:d8e1a068393243dbf93f49',
    messagingSenderId: '198328821100',
    projectId: 'crud-19417',
    authDomain: 'crud-19417.firebaseapp.com',
    storageBucket: 'crud-19417.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKcWClfwA1mrQnPj_a-fNbOKG67Fjka1s',
    appId: '1:686950052046:android:46adbf8d7acbe56aee209f',
    messagingSenderId: '686950052046',
    projectId: 'flutter-project-af49b',
    storageBucket: 'flutter-project-af49b.appspot.com',
  );

}